### ISSUE TITLE
Any chance the redis dependency could be relaxed? Or at least updated?

### ISSUE THREAD

**Issue by agibralter** [thoughtbot/daikon#1]
https://rubygems.org/gems/redis is already at 2.2.0. A lot of my other gems depend on ~> 2.2.0...

**Comment by qrush** [comment]
Sure, no problem. Coming right up!

**Comment by qrush** [comment]
Just pushed 0.8.7 with relaxed constraints:

https://rubygems.org/gems/daikon/versions/0.8.7

Let me know if this fixes it!

**Comment by agibralter** [comment]
Awesome! Thank you for the quick response!
